name: Build and Deploy to IIS

on:
  push:
    branches:
      - deploy  

jobs:
  build-and-deploy:
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

   
    - name: Build React Frontend
      run: |  
        npm install
        npm run build

    

    
    - name: Deploy Frontend to IIS
      uses: microsoft/webdeploy@v1
      with:
        source: './frontend/build'
        dest: 'contentPath=Default Web Site/Frontend,ComputerName=https://$SERVER_IP/msdeploy.axd?site=Default Web Site,UserName=$IIS_USERNAME,Password=$IIS_PASSWORD,AuthType=Basic'
        enableRule: DoNotDeleteRule
        allowUntrusted: true
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        IIS_USERNAME: ${{ secrets.IIS_USERNAME }}
        IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}

    
